In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
print(type(a))
print(a.shape) #shape是静态成员，不是成员函数
print(a[0], a[1], a[2])
print(a)

<type 'numpy.ndarray'>
(3,)
(1, 2, 3)
[1 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]]) 
print(b.shape)

(2, 3)


In [7]:
a = np.zeros((2, 2))
print(a)

b = np.ones((1, 2))
print(b)

c = np.full((2, 2), 7)
print(c)

d = np.eye(2)
print(d)

e = np.random.random((2, 2))
print(e)

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[7 7]
 [7 7]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.29581912  0.80195093]
 [ 0.15842728  0.55155474]]


In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = a[:2, 1 : 3]
# :2表示第0行和第一行， 1:3表示第一列和第二列 左闭右开区间

In [10]:
b

array([[2, 3],
       [6, 7]])

In [11]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[1, :])

[5 6 7 8]


In [12]:
print(a[:, 1])

[ 2  6 10]


In [13]:
b = np.array(a[:, 1])
b[0] = 1
print(b)
print(a)


[ 1  6 10]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])
a[np.arange(4), b]

array([ 1,  6,  7, 11])

In [20]:
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [24]:
a = np.array([[1, 2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)
a[bool_idx]
print(a > 2)

[[False False]
 [ True  True]
 [ True  True]]
[[False False]
 [ True  True]
 [ True  True]]


In [25]:
a[bool_idx]

array([3, 4, 5, 6])

In [28]:
x = np.array([[1, 2],[3, 4]], dtype = np.float64)
y = np.array([[5, 6], [7, 8]], dtype = np.float64)

print(x + y)
print(x - y)
print(np.divide(x, y))
print(x * y)

#注意乘法与matlab中不同，为对应的元素各自相乘

[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[  5.  12.]
 [ 21.  32.]]


In [29]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v, w))

print(x.dot(y))
print(np.dot(x, y))

219
219
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [31]:
x = np.array([[1,2],[3,4]])
print(np.sum(x))
print(np.sum(x, axis = 0)) #axis = 0 表示列想加
print(np.sum(x, axis = 1)) #axis = 1 表示行相加

10
[4 6]
[3 7]


In [32]:
x = np.array([[1,2], [3,4]])
print(x)
print(x.T)
v = np.array([1,2,3])
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [35]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)

print(y)
for i in range(4):
    y[i, :] = x[i, :] + v
    
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [37]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
